apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: 533267189619.dkr.ecr.us-west-2.amazonaws.com/quickdispatch-managment:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db:3306/userForge
        - name: SPRING_DATASOURCE_PORT
          value: "3306"
        - name: SPRING_DATASOURCE_DATABASE
          value: userForge
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: KAFKA_CLUSTER_URL
          value: 80.0.20.131:9092

---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
